source 'https://github.com/CocoaPods/Specs.git'

target 'PGPKit', :exclusive => true do
  pod "PGPKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PGPKit", :path => "../"

  pod 'FBSnapshotTestCase'
end
